// quizzes.js

const quizzes = [
    {
      _id: 1,
      title: "Q1 - HTML",
      type: "Graded Quiz",
      point: 100,
      status: "Published",
      assignmentGroup: "Quizzes",
      shuffleAnswer: "Yes",
      timeLimit: "20",
      multipleAttempts: "No",
      howManyAttempts: "1",
      showCorrectAnswers: "Immediately",
      oneQuestionAtATime: "Yes",
      webcamRequired: "No",
      lockQuestionsAfterAnswering: "No",
      dueDate: "2024-03-25",
      availableDate: "2024-03-25",
    },
    {
      _id: 2,
      title: "Q2 - CSS Basics",
      type: "Practice Quiz",
      point: 50,
      status: "Unpublished",
      assignmentGroup: "Assignments",
      shuffleAnswer: "No",
      timeLimit: "10",
      multipleAttempts: "Yes",
      howManyAttempts: "3",
      showCorrectAnswers: "After Due Date",
      oneQuestionAtATime: "No",
      webcamRequired: "Yes",
      lockQuestionsAfterAnswering: "No",
      dueDate: "2024-04-10",
      availableDate: "2024-04-01",
    },
    {
      _id: 3,
      title: "Q3 - JavaScript Functions",
      type: "Graded Survey",
      point: 80,
      status: "Published",
      assignmentGroup: "Exams",
      shuffleAnswer: "Yes",
      timeLimit: "15",
      multipleAttempts: "Yes",
      howManyAttempts: "5",
      showCorrectAnswers: "Never",
      oneQuestionAtATime: "Yes",
      webcamRequired: "No",
      lockQuestionsAfterAnswering: "Yes",
      dueDate: "2024-05-15",
      availableDate: "2024-05-01",
    },
    {
      _id: 4,
      title: "Q4 - Responsive Design",
      type: "Ungraded Survey",
      point: 0,
      status: "Unpublished",
      assignmentGroup: "Projects",
      shuffleAnswer: "No",
      timeLimit: "30",
      multipleAttempts: "No",
      howManyAttempts: "1",
      showCorrectAnswers: "After Quiz is Graded",
      oneQuestionAtATime: "No",
      webcamRequired: "No",
      lockQuestionsAfterAnswering: "No",
      dueDate: "2024-06-01",
      availableDate: "2024-05-20",
    },
    {
      _id: 5,
      title: "Q5 - Advanced JavaScript",
      type: "Graded Quiz",
      point: 120,
      status: "Published",
      assignmentGroup: "Exams",
      shuffleAnswer: "Yes",
      timeLimit: "25",
      multipleAttempts: "Yes",
      howManyAttempts: "Unlimited",
      showCorrectAnswers: "After Each Attempt",
      oneQuestionAtATime: "Yes",
      webcamRequired: "Yes",
      lockQuestionsAfterAnswering: "Yes",
      dueDate: "2024-07-01",
      availableDate: "2024-06-15",
    },
  ];
  
  export default quizzes;
  